# Generated by Django 2.2.2 on 2020-08-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_media', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='', max_length=65000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=65000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ChatUserInRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('croom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.FileField(upload_to='uplaods/chatmedia/')),
                ('chatm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatMessage')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='croom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo'),
        ),
    ]
