# Generated by Django 2.2.2 on 2020-08-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatuserinroom',
            unique_together={('croom', 'cuser')},
        ),
    ]
