# Generated by Django 2.2.2 on 2020-08-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0002_auto_20200807_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_media', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='', max_length=65000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chatmessagemedia',
            name='media_url',
            field=models.FileField(upload_to='uploads/chatmedia/'),
        ),
        migrations.CreateModel(
            name='SingleChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='accounts.UserInfo')),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='accounts.UserInfo')),
                ('suser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='accounts.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChatMessageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.FileField(upload_to='uploads/schatmedia/')),
                ('chatm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.SingleChatMessage')),
            ],
        ),
        migrations.AddField(
            model_name='singlechatmessage',
            name='croom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.SingleChatRoom'),
        ),
        migrations.AddField(
            model_name='singlechatmessage',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo'),
        ),
    ]
