# Generated by Django 2.2.2 on 2020-08-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200808_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechatroom',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='accounts.UserInfo'),
        ),
    ]
